### ISSUE TITLE
Unlocalized [body]

### ISSUE THREAD

**Issue by yalov** [magico13/MagiCore#5]
https://github.com/magico13/MagiCore/blob/20b6354a7412a59f8ee7016d700ad4825730d1dd/MagiCore/StringTranslation.cs#L78

`Planetarium.fetch.CurrentMainBody.GetDisplayName ()`

**Comment by linuxgurugamer** [comment]
Yalov,
I've adopted this, please post some more details in my fork.  Other than replacing the NA with a localized string, the "body" in the original string should never be seen, it should be replaced by that line

**Comment by yalov** [comment]
@linuxgurugamer, I already do not remember where I seen unlocalized body name in game, but this message was about
`Planetarium.fetch.CurrentMainBody.bodyName` — unlocalized body name
`Planetarium.fetch.CurrentMainBody.GetDisplayName ()` — localized body name
So I thought what in the line should be `GetDisplayName ()`

**Comment by linuxgurugamer** [comment]
Just an FYI, I fixed this in my release
